#!/bin/sh

install()
{
  apt-get "$@" install curl jq bc python3-boto gperf ec2-api-tools g++ \
    cloud-utils linux-headers-generic linux-libc-dev gcc-10-plugin-dev \
    autoconf automake bison flex nasm ruby patch git intltool pkg-config \
    libncurses5-dev libreadline-dev libpopt-dev libpcre3-dev uuid-dev \
    expect tcl libtool libgettextpo-dev libattr1-dev zlib1g-dev libbz2-dev \
    libicu-dev libperl-dev cmake libdb5.3-dev libxtables-dev zip ccache gawk \
     mozjs* libnet-amazon-s3-tools-perl &&
  \


  return "$?"
}

install "$@"
exit "$?"

